name: show_characters_viewer
description: Show Character Viewer
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_device_type: ^0.4.0
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_portal: ^1.1.4
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  pull_to_refresh: ^2.0.0
  riverpod_annotation: ^2.1.1

 
dev_dependencies:
  build_runner: ^2.4.6
  flutter_flavorizr: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  json_serializable: ^6.7.1
  mockito: ^5.0.0
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.4
  very_good_analysis: ^5.0.0

  
flutter:
  uses-material-design: true
  generate: true
